# Generated by Django 3.2.7 on 2021-10-02 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('contacts', models.ManyToManyField(to='main.ChatUser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='main.chatuser')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='main.chatuser')),
            ],
            options={
                'ordering': ('sent_at',),
            },
        ),
        migrations.AddField(
            model_name='chatuser',
            name='messages',
            field=models.ManyToManyField(related_name='_main_chatuser_messages_+', through='main.Message', to='main.ChatUser'),
        ),
    ]
