# Generated by Django 4.0.2 on 2022-02-06 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211002_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='messages',
            field=models.ManyToManyField(through='main.Message', to=settings.AUTH_USER_MODEL),
        ),
    ]
