# Generated by Django 3.2 on 2022-05-17 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_chatuser_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='messages',
            field=models.ManyToManyField(related_name='_main_chatuser_messages_+', through='main.Message', to=settings.AUTH_USER_MODEL),
        ),
    ]
